###############################################################################
# Caterva2 - On demand access to remote Blosc2 data repositories
#
# Copyright (c) 2023 The Blosc Developers <blosc@blosc.org>
# https://www.blosc.org
# License: GNU Affero General Public License v3.0
# See LICENSE.txt for details about copyright and rights to use.
###############################################################################

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "caterva2"
requires-python = ">3.10"
readme = "README.md"
authors = [
    {name = "Blosc Development Team", email = "contact@blosc.org"},
]
dynamic = ["version", "description"]
keywords = ["pubsub", "blosc2"]
license = {text = "GNU Affero General Public License version 3"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
]
dependencies = [
    "blosc2>=2.4.0",  # TODO: try to remove this dependency, and move to services, if possible
    "fastapi",  # TODO: ditto
    "fastapi_websocket_pubsub",  # TODO: ditto
    "safer",  # TODO: ditto
    "tqdm",  # TODO: ditto, but move into clients
    "httpx",
    "numpy",
    "rich",
]

[tool.hatch.version]
path = "caterva2/__init__.py"

[project.optional-dependencies]
services = [
    # TODO: try to add these dependencies here, and remove them from caterva2, if possible
    # "blosc2>=2.4.0",
    # "fastapi",
    # "fastapi_websocket_pubsub",
    # "safer",
    "uvicorn",
    "watchfiles",
]
clients = [
    # "tqdm",
    "rich",
    "textual",
]
test = [
    "pytest",
]

[project.urls]
Home = "https://github.com/Blosc/Caterva2"

[project.services]
cat2bro = "caterva2.services.bro:main"
cat2pub = "caterva2.services.pub:main"
cat2sub = "caterva2.services.sub:main"

[project.clients]
cat2cli = "caterva2.clients.cli:main"
cat2tbrowser = "caterva2.clients.tbrowser:main"
