# This workflow will run on an external ubicloud arm64 runner on latest ubuntu (ubicloud standard)

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubicloud-standard-2-arm

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        python -m pip install --upgrade pip
        pip install -e '.[tests]'
    - name: Test with pytest
      run: |
        python -m pytest
    - name: Test building docs
      run: |
        python -m pip install -r doc/requirements.txt
        sphinx-build doc doc/html
